version: '3.8'

services:
  app:
    build: .
    ports:
      - "8501:8501"
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: root
      DB_DATABASE: ed_bert
      DB_DIALECT: mysql
      DB_DRIVER: pymysql
    depends_on:
      - db
  db:
    image: mysql:8.0.32
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ed_bert
    ports:
      - "3306:3306"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

